dist: trusty
sudo: false
group: beta
language: node_js

node_js:
  - "8.12.0"

install:
  - npm ci

script:
  - # Run all tests

jobs:
  # XXX fast_finish doesn't work with stages yet. See
  # https://github.com/travis-ci/travis-ci/issues/8425
  # --elopio - 20180531
  fast_finish: true
  allow_failures:
    - env: SOLC_NIGHTLY=true
  include:
    - stage: tests
      name: "Unit tests"
      script: npm run test
